<?xml version='1.0' encoding='UTF-8'?>
<!--
Copyright (C) 2014 erbjuder.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<definitions 
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
    xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" 
    xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="urn:generic.com:Global:TransactionLogger"  
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    targetNamespace="urn:generic.com:Global:TransactionLogger" 
    name="TransactionLogAsynchronous">
    
    
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:generic.com:Global:TransactionLogger"  schemaLocation="Log_Service_Asynchronous.xsd"/>
        </xsd:schema>
    </types>
    


    <message name="Transactions">
        <part name="Transactions" element="tns:Transactions"/>
    </message>
   
    
    <portType name="TransactionLogAsynchronous">
        <operation name="Persist">
            <input message="tns:Transactions"/>
        </operation>
    </portType>
    
    <binding name="TransactionLogAsynchronous_Binding" type="tns:TransactionLogAsynchronous">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="Persist">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
        </operation>
    </binding>
    

 
    <service name="TransactionLogAsynchronousService">
        <port name="TransactionLogAsynchronous_InPort" binding="tns:TransactionLogAsynchronous_Binding">
            <soap:address location="http://localhost:8080"/>
        </port>
    </service>
 
    
</definitions>
